# Import dataset

In [1]:
import kagglehub
import pandas as pd
import os

# Download latest version
path = kagglehub.dataset_download(
    "bismasajjad/global-ai-job-market-and-salary-trends-2025"
)

print("Dataset path:", path)

# Check files
print(os.listdir(path))

C:\Users\shara\anaconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Dataset path: C:\Users\shara\.cache\kagglehub\datasets\bismasajjad\global-ai-job-market-and-salary-trends-2025\versions\2
['ai_job_dataset.csv', 'ai_job_dataset1.csv']

# Data understanding

In [3]:
# load dataset
df = pd.read_csv(f"{path}/ai_job_dataset.csv")

In [6]:
# view the dataset - first 5 
df.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [8]:
# column names
df.columns

Index(['job_id', 'job_title', 'salary_usd', 'salary_currency',
       'experience_level', 'employment_type', 'company_location',
       'company_size', 'employee_residence', 'remote_ratio', 'required_skills',
       'education_required', 'years_experience', 'industry', 'posting_date',
       'application_deadline', 'job_description_length', 'benefits_score',
       'company_name'],
      dtype='object')

In [10]:
# check for null values
df.isnull().sum()

job_id                    0
job_title                 0
salary_usd                0
salary_currency           0
experience_level          0
employment_type           0
company_location          0
company_size              0
employee_residence        0
remote_ratio              0
required_skills           0
education_required        0
years_experience          0
industry                  0
posting_date              0
application_deadline      0
job_description_length    0
benefits_score            0
company_name              0
dtype: int64

In [12]:
# check for duplicates
df.duplicated().sum()

np.int64(0)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  15000 non-null  object
 1   job_title               15000 non-null  object
 2   salary_usd              15000 non-null  int64
 3   salary_currency         15000 non-null  object
 4   experience_level        15000 non-null  object
 5   employment_type         15000 non-null  object
 6   company_location        15000 non-null  object
 7   company_size            15000 non-null  object
 8   employee_residence      15000 non-null  object
 9   remote_ratio            15000 non-null  int64
 10  required_skills         15000 non-null  object
 11  education_required      15000 non-null  object
 12  years_experience        15000 non-null  int64
 13  industry                15000 non-null  object
 14  posting_date            15000 non-null  object
 15  application_deadline    15000 non-null  object
 16  job_description_length  15000 non-null  int64
 17  benefits_score          15000 non-null  float64
 18  company_name            15000 non-null  object
dtypes: float64(1), int64(4), object(14)
memory usage: 2.2+ MB

In [16]:
# data quality
df['salary_usd'].describe()

count     15000.000000
mean     115348.965133
std       60260.940438
min       32519.000000
25%       70179.750000
50%       99705.000000
75%      146408.500000
max      399095.000000
Name: salary_usd, dtype: float64

In [18]:
# data quality
df['years_experience'].describe()

count    15000.000000
mean         6.253200
std          5.545768
min          0.000000
25%          2.000000
50%          5.000000
75%         10.000000
max         19.000000
Name: years_experience, dtype: float64

In [20]:
# data quality
df['remote_ratio'].unique()

array([ 50, 100,   0])

# Data Cleaning

In [23]:
# FIX THE DATATYPE
df['posting_date']=pd.to_datetime(df['posting_date'])
df['application_deadline']=pd.to_datetime(df['application_deadline'])

In [25]:
df['salary_currency'].unique()

array(['USD', 'EUR', 'GBP'], dtype=object)

In [27]:
df['job_title'].unique()

array(['AI Research Scientist', 'AI Software Engineer', 'AI Specialist',
       'NLP Engineer', 'AI Consultant', 'AI Architect',
       'Principal Data Scientist', 'Data Analyst',
       'Autonomous Systems Engineer', 'AI Product Manager',
       'Machine Learning Engineer', 'Data Engineer', 'Research Scientist',
       'ML Ops Engineer', 'Robotics Engineer', 'Head of AI',
       'Deep Learning Engineer', 'Data Scientist',
       'Machine Learning Researcher', 'Computer Vision Engineer'],
      dtype=object)

In [29]:
df['employment_type'].unique()

array(['CT', 'FL', 'PT', 'FT'], dtype=object)

In [31]:
df['company_size'].unique()

array(['M', 'L', 'S'], dtype=object)

In [33]:
df=df.drop(columns=['job_description_length'])

In [35]:
# mapping
experience_map = {
    'EN': 'Entry',
    'MI': 'Mid',
    'SE': 'Senior',
    'EX': 'Executive'
}
df['experience_level'] = df['experience_level'].map(experience_map)

In [37]:
#mapping
employment_map={
    'CT':'Contract',
    'FT':'Full Time',
    'PT':'Part Time',
    'FL': 'Freelance'
}

df['employment_type']=df['employment_type'].map(employment_map)

In [39]:
# mapping
company_map={
    "M":"Mid",
    "L":"Large",
    "S":"Small"
}
df['company_size']=df['company_size'].map(company_map)

In [41]:
# remove unwanted space and convert to lower
df['company_location']=(
    df['company_location'].str.strip()
    .str.lower()
)

In [43]:
df['employee_residence']=(
    df['employee_residence'].str.strip()
    .str.lower()
)

# Data Transformation

In [46]:
# create separate dataframe for skills

skills_df=df[['job_id','required_skills']].copy() # required rows only 

skills_df['required_skills']=skills_df['required_skills'].str.split(",") # separated using comma as delimiter

# convert each skill into separate row
skills_df=skills_df.explode('required_skills')

# remove extra space
skills_df['required_skills']=skills_df['required_skills'].str.strip()

# Rename the column 
skills_df=skills_df.rename(columns={'required_skills':'skill'})

skills_df.head(10)

    job_id          skill
0  AI00001        Tableau
0  AI00001        PyTorch
0  AI00001     Kubernetes
0  AI00001          Linux
0  AI00001            NLP
1  AI00002  Deep Learning
1  AI00002            AWS
1  AI00002    Mathematics
1  AI00002         Python
1  AI00002         Docker

In [48]:
# create separata datafram for main dataset 

cleaned_jobs_df=df.drop(columns=['required_skills'])

cleaned_jobs_df.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,education_required,years_experience,industry,posting_date,application_deadline,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,Senior,Contract,china,Mid,china,50,Bachelor,9,Automotive,2024-10-18,2024-11-07,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,Entry,Contract,canada,Mid,ireland,100,Master,1,Media,2024-11-20,2025-01-11,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,Mid,Freelance,switzerland,Large,south korea,0,Associate,2,Education,2025-03-18,2025-04-07,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,Senior,Freelance,india,Mid,india,50,PhD,7,Consulting,2024-12-23,2025-02-24,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,Entry,Part Time,france,Small,singapore,100,Master,0,Media,2025-04-15,2025-06-23,6.6,Advanced Robotics

# Export CSV Files

In [51]:
# main dataset 
cleaned_jobs_df.to_csv("cleaned_jobs.csv",index=False)

# skills dataset 
skills_df.to_csv("skills_job.csv",index=False)

print("Successfully exported to CSV Files")

Successfully exported to CSV Files